# Generated by Django 2.0.3 on 2018-03-26 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analytic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=64)),
                ('ip_server', models.CharField(max_length=64)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('project', models.CharField(max_length=256)),
                ('text', models.CharField(max_length=256)),
                ('type', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=64)),
            ],
        ),
    ]
